apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca
  namespace: default
spec:
  commonName: ca.webhook.cert-manager
  duration: 43800h
  isCA: true
  issuerRef:
    name: cert-manager-webhook-selfsign
  secretName: cert-manager-webhook-ca
