apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: webhook
    release: cert-manager
  name: cert-manager-webhook-ca-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-ca-sync
subjects:
- kind: ServiceAccount
  name: cert-manager-webhook-ca-sync
  namespace: default
