apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  labels:
    app: webhook
    chart: webhook-v0.6.4
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-ca
  namespace: default
spec:
  ca:
    secretName: cert-manager-webhook-ca
