apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: webhook
    release: cert-manager
  name: cert-manager-webhook
webhooks:
- clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.certmanager.k8s.io/v1beta1/certificates
  failurePolicy: Fail
  name: certificates.admission.certmanager.k8s.io
  namespaceSelector:
    matchExpressions:
    - key: certmanager.k8s.io/disable-validation
      operator: NotIn
      values:
      - "true"
    - key: name
      operator: NotIn
      values:
      - default
  rules:
  - apiGroups:
    - certmanager.k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - certificates
- clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.certmanager.k8s.io/v1beta1/issuers
  failurePolicy: Fail
  name: issuers.admission.certmanager.k8s.io
  namespaceSelector:
    matchExpressions:
    - key: certmanager.k8s.io/disable-validation
      operator: NotIn
      values:
      - "true"
    - key: name
      operator: NotIn
      values:
      - default
  rules:
  - apiGroups:
    - certmanager.k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - issuers
- clientConfig:
    service:
      name: kubernetes
      namespace: default
      path: /apis/admission.certmanager.k8s.io/v1beta1/clusterissuers
  failurePolicy: Fail
  name: clusterissuers.admission.certmanager.k8s.io
  namespaceSelector:
    matchExpressions:
    - key: certmanager.k8s.io/disable-validation
      operator: NotIn
      values:
      - "true"
    - key: name
      operator: NotIn
      values:
      - default
  rules:
  - apiGroups:
    - certmanager.k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterissuers
