apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cert-manager
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    release: cert-manager
  name: cert-manager-edit
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
